project:
  type: website
  output-dir: docs

website:
  title: "Data Engineering Assessment 1"
  favicon: Logo.png
  navbar:
    logo: Logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Data Visualisation.qmd
      - Reflection.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



