project:
  type: website
  output-dir: docs

website:
  title: "Data Engineering Assessment 1"
  favicon: Logo.png
  navbar:
    logo: Logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: "Data Visualisation.qmd"
        text: Data Visualisation
      - href: Reflection.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



